module.exports.config = {
  name: "putul",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "ashik",
  author: "ashik",
  role: 2,
  description: "Cute couple love lines for Putul 💖",
  commandCategory: "love",
  usages: "/putul",
  cooldowns: 5
};

module.exports.run = async function({ api, event }) {

  const lines = [
    "💖 Putul, tumi amar chotto ekta shukh er duniya.",
    "🌸 Tumi chara amar din gulo shunno mone hoy.",
    "💞 Putul, tumi amar heart er most beautiful chapter.",
    "🥺 Tomar hasi dekhle mon ta shanti peye jay.",
    "❤️ Ami chai tumi shob shomoy amar pashe thako.",
    "🌙 Raat er chader moto tumi amar shopner alo.",
    "✨ Putul, tumi amar life er sweetest addiction.",
    "💘 Tomar kotha chara din ta incomplete lage.",
    "🌸 Tumi amar chotto universe er queen.",
    "💖 Ami tomay chara kichu imagine korte pari na.",
    "🥰 Putul, tumi amar smile er main reason.",
    "💞 Tomar voice amar jonno ekta comfort zone.",
    "❤️ Tumi amar moner bhitore shobcheye special.",
    "🌙 Raat e tomay niye onek shopno dekhi.",
    "💘 Putul, tumi amar real happiness.",
    "✨ Tomar presence amar life ke color dey.",
    "💖 Ami chai tomay shob shomoy protect korte.",
    "🌸 Tumi amar daily motivation.",
    "🥺 Tomay na dekhle mon kharap hoye jay.",
    "💞 Putul, tumi amar forever person.",
    "❤️ Tumi amar shob emotions er center.",
    "🌙 Tomar sathe kotha bolle shanti lage.",
    "💘 Ami tomay onek beshi valobashi Putul.",
    "✨ Tumi amar dream girl in real life.",
    "💖 Tomar smile amar duniya.",
    "🌸 Putul, tumi amar heartbeat.",
    "🥰 Tomar sathe thaka mane happiness.",
    "💞 Tumi chara ami incomplete.",
    "❤️ Putul, tumi amar chirokaler bondhu o valobasha.",
    "🌙 Tomay niye amar future imagine kori.",
    "💘 Tumi amar shobcheye priyo manus.",
    "✨ Putul, tumi amar life er light.",
    "💖 Tomar jonno ami shob kichu korte pari.",
    "🌸 Tumi amar moner sweetest corner.",
    "🥺 Tomar ekta message amar din bhalo kore dey.",
    "💞 Putul, tumi amar endless story.",
    "❤️ Ami tomay harate chai na kokhono.",
    "🌙 Tumi amar shob dream er reason.",
    "💘 Putul, tumi amar perfect imperfection.",
    "✨ Tomar sathe shob kichu special lage.",
    "💖 Tumi amar life er best decision.",
    "🌸 Putul, tumi amar forever love.",
    "🥰 Tomar kotha vablei smile ashe.",
    "💞 Tumi amar moner shobcheye close.",
    "❤️ Ami tomay onek miss kori Putul.",
    "🌙 Tumi amar shobcheye shundor feeling.",
    "💘 Putul, tumi amar world.",
    "✨ Tomar jonno ami always here.",
    "💖 Tumi amar chirodin er valobasha.",
    "🌸 Putul, tumi amar soulmate vibe.",
    "🥰 Tomar sathe shob moment priceless.",
    "💞 Tumi amar life er sweetest person.",
    "❤️ Ami tomay niye future bani.",
    "🌙 Putul, tumi amar dream reality.",
    "💘 Tumi chara ami adhoora.",
    "✨ Tomar smile amar oxygen.",
    "💖 Putul, tumi amar everything.",
    "🌸 Tumi amar heart er permanent guest.",
    "🥺 Ami tomay onek care kori.",
    "💞 Putul, tumi amar peace.",
    "❤️ Tumi amar forever & always.",
    "🌙 Tomar sathe life ta perfect.",
    "💘 Putul, tumi amar jan.",
    "✨ Tumi amar shob kichur uttor.",
    "💖 Ami tomay chere jete pari na.",
    "🌸 Putul, tumi amar duniya.",
    "🥰 Tomar jonno ami always loyal.",
    "💞 Tumi amar heart er owner.",
    "❤️ Putul, tumi amar real love story."
  ];

  const pick = lines[Math.floor(Math.random() * lines.length)];

  return api.sendMessage(
    `💌 𝗖𝗼𝘂𝗽𝗹𝗲 𝗠𝗲𝘀𝘀𝗮𝗴𝗲 💌\n\n${pick}\n\n💖 - ashik`,
    event.threadID,
    event.messageID
  );
};
